/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadg1.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadg1.accesoadatos.MateriaData;
import universidadg1.entidades.Materia;

/**
 *
 * @author Gonza
 */
public class FormularioMateria extends javax.swing.JInternalFrame {

    private MateriaData matData = new MateriaData();
    private Materia materiaActual = null;

    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbBuscarMateria = new javax.swing.JButton();
        jbNuevoMateria = new javax.swing.JButton();
        jbEliminarMateria = new javax.swing.JButton();
        jbGuardarMateria = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtEstado = new javax.swing.JRadioButton();
        jtAnio = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(208, 208, 250));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Materia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Año:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jbBuscarMateria.setText("Buscar");
        jbBuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMateriaActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, -1));

        jbNuevoMateria.setText("Nuevo");
        jbNuevoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoMateriaActionPerformed(evt);
            }
        });
        jPanel2.add(jbNuevoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jbEliminarMateria.setText("Eliminar");
        jbEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarMateriaActionPerformed(evt);
            }
        });
        jPanel2.add(jbEliminarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jbGuardarMateria.setText("Guardar");
        jbGuardarMateria.setEnabled(false);
        jbGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarMateriaActionPerformed(evt);
            }
        });
        jPanel2.add(jbGuardarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jtEstado.setText("Activo");
        jPanel2.add(jtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        jPanel2.add(jtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, -1));
        jPanel2.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, -1));
        jPanel2.add(jtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, 382, 14));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 382, 20));

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarMateriaActionPerformed
        // TODO add your handling code here:
        try {
            Integer idMateria = Integer.parseInt(jtCodigo.getText());
            // Llama a tu método para eliminar la materia
            matData.eliminarMateria(idMateria);
            JOptionPane.showMessageDialog(this, "Materia eliminada con éxito");
            // Limpia los campos después de la eliminación
            limpiarCampos();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido");
        }
    }//GEN-LAST:event_jbEliminarMateriaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMateriaActionPerformed
        // TODO add your handling code here:

        try {
            Integer idMateria = Integer.parseInt(jtCodigo.getText());
            materiaActual = matData.buscarMateria(idMateria);
            if (materiaActual != null) {
                jtNombre.setText(materiaActual.getNombre());
                jtAnio.setText(String.valueOf(materiaActual.getAnioMateria()));
                jtEstado.setSelected(materiaActual.isActivo());
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido");
//            limpiarCampos();
        }
    }//GEN-LAST:event_jbBuscarMateriaActionPerformed

    private void jbGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarMateriaActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = jtNombre.getText();
            Integer anio = Integer.parseInt(jtAnio.getText());
            boolean estado = jtEstado.isSelected();

            Materia nuevaMateria = new Materia(nombre, anio, estado);
            matData.guardarMateria(nuevaMateria);
            limpiarCampos();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido");

        }
    }//GEN-LAST:event_jbGuardarMateriaActionPerformed

    private void jbNuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoMateriaActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        jtCodigo.setEnabled(false);
        jbGuardarMateria.setEnabled(true);
        jbBuscarMateria.setEnabled(false);
    }//GEN-LAST:event_jbNuevoMateriaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jtCodigo.setEnabled(true);
        jbBuscarMateria.setEnabled(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void limpiarCampos() {
        jtCodigo.setText("");
        jtNombre.setText("");
        jtAnio.setText("");
        jtEstado.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbBuscarMateria;
    private javax.swing.JButton jbEliminarMateria;
    private javax.swing.JButton jbGuardarMateria;
    private javax.swing.JButton jbNuevoMateria;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JRadioButton jtEstado;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
