/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadg1.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadg1.accesoadatos.AlumnoData;
import universidadg1.accesoadatos.InscripcionData;
import universidadg1.accesoadatos.MateriaData;
import universidadg1.entidades.Alumno;
import universidadg1.entidades.Inscripcion;
import universidadg1.entidades.Materia;

/**
 *
 * @author Gonza
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {
    private List<Materia> listaMat;
    private List<Alumno> listaAlu;
    
    private InscripcionData inscData;
    private MateriaData matData;
    private AlumnoData alData;
    
    private DefaultTableModel tablaMateria;
    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        
        alData = new AlumnoData();
        listaAlu = alData.listaAlumnos();
        tablaMateria = new DefaultTableModel();
        inscData = new InscripcionData();
        matData = new MateriaData();
        cargarAlumnos();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rinsc = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbInscribirAlumno = new javax.swing.JButton();
        jbAnularInscripcion = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jcAlumno = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jrMateriaInscripta = new javax.swing.JRadioButton();
        jrMateriasNOinsc = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 208, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione un Alumno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Listado de Materias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jbInscribirAlumno.setText("Inscribir");
        jbInscribirAlumno.setEnabled(false);
        jbInscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jbInscribirAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jbAnularInscripcion.setText("Anular Inscripcion");
        jbAnularInscripcion.setEnabled(false);
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });
        jPanel1.add(jbAnularInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 350, 150));

        jPanel1.add(jcAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 190, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 350, 20));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, 20));

        rinsc.add(jrMateriaInscripta);
        jrMateriaInscripta.setText("Materias Inscriptas");
        jrMateriaInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriaInscriptaActionPerformed(evt);
            }
        });
        jPanel1.add(jrMateriaInscripta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        rinsc.add(jrMateriasNOinsc);
        jrMateriasNOinsc.setText("Materias NO inscriptas");
        jrMateriasNOinsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriasNOinscActionPerformed(evt);
            }
        });
        jPanel1.add(jrMateriasNOinsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrMateriaInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriaInscriptaActionPerformed
        // TODO add your handling code here:
        borrarFilaTabla();
        jrMateriasNOinsc.setSelected(false);
        cargarDatosInscriptas();
        jbAnularInscripcion.setEnabled(true);
        jbInscribirAlumno.setEnabled(false);
    }//GEN-LAST:event_jrMateriaInscriptaActionPerformed

    private void jrMateriasNOinscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriasNOinscActionPerformed
        // TODO add your handling code here:
        borrarFilaTabla();
        jrMateriaInscripta.setSelected(false);
        cargarDatosNoInscriptas();
        jbAnularInscripcion.setEnabled(false);
        jbInscribirAlumno.setEnabled(true);
    }//GEN-LAST:event_jrMateriasNOinscActionPerformed

    private void jbInscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirAlumnoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jtMaterias.getSelectedRow();
        if(filaSeleccionada!= -1){
            Alumno a=(Alumno)jcAlumno.getSelectedItem();
            int idMateria=(Integer)tablaMateria.getValueAt(filaSeleccionada, 0);
            String nombreMateria =(String) tablaMateria.getValueAt(filaSeleccionada, 1);
            int anio=(Integer)tablaMateria.getValueAt(filaSeleccionada, 2);
            Materia m=new Materia(idMateria, nombreMateria, anio, true);
            
            Inscripcion i=new Inscripcion(a, m, 0);
            inscData.guardarInscripcion(i);
            JOptionPane.showMessageDialog(this, "Alumno inscripto");
            borrarFilaTabla();
        }
    }//GEN-LAST:event_jbInscribirAlumnoActionPerformed

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jtMaterias.getSelectedRow();
        if(filaSeleccionada!= -1){
            Alumno a=(Alumno)jcAlumno.getSelectedItem();
            int idMateria=(Integer)tablaMateria.getValueAt(filaSeleccionada, 0);
            
            inscData.borrarInscripcionMateriaAlumno(a.getIdAlumno(), idMateria);
            borrarFilaTabla();
        }
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void cargarAlumnos(){
        for(Alumno item: listaAlu){
            jcAlumno.addItem(item);
        }
    }

    private void armarCabeceraTabla(){
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        
        for (Object it : filaCabecera) {
            tablaMateria.addColumn(it);
        }
        jtMaterias.setModel(tablaMateria);
        
    }
    
    private void borrarFilaTabla(){
        int indice = tablaMateria.getRowCount();
        
        for (int i = indice; i > 0; i--) {
            tablaMateria.removeRow(0);
        }
    }
    
    private void cargarDatosNoInscriptas(){
        borrarFilaTabla();
        Alumno selec = (Alumno) jcAlumno.getSelectedItem();
        listaMat = inscData.obtenerMateriasNOCursadas(selec.getIdAlumno());
        System.out.println("materia no inscrita"+ listaMat);
        for(Materia m: listaMat){
            tablaMateria.addRow (new Object[] {m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
        }
    }   
    private void cargarDatosInscriptas(){
        borrarFilaTabla();
        Alumno selec = (Alumno) jcAlumno.getSelectedItem();
        listaMat = inscData.obtenerMateriasCursadas(selec.getIdAlumno());
        System.out.println("materia inscrita"+ listaMat);
         for(Materia m: listaMat){
            tablaMateria.addRow (new Object[] {m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
        }
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribirAlumno;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcAlumno;
    private javax.swing.JRadioButton jrMateriaInscripta;
    private javax.swing.JRadioButton jrMateriasNOinsc;
    private javax.swing.JTable jtMaterias;
    private javax.swing.ButtonGroup rinsc;
    // End of variables declaration//GEN-END:variables
}
